### ISSUE TITLE
[BUG] Azure CLI is not installed 

### ISSUE THREAD

**Issue by JK87iab** [databricks/databricks-vscode#784]
Just set up vs code on a new machine mac M2

Installed az cli, and az login is working in the terminal.

But hitting configure databricks -> paste workspace url -> select azure cli. 
I get only the pop up msg that Azure CLI is not installed. 

Not sure how to debug that

Extension version: v1.0.0 
Vs code:  1.79.2

**Comment by mgyucht** [comment]
@JK87iab Thanks for raising this. It is possible that the PATH used for your terminal is not the same as that used for VS Code. You can verify this by viewing logs for VS Code (in the command palette, "Databricks: Open full logs") and checking for an entry containing ENOENT. You can try opening VS Code from the terminal, which will inherit the terminal's environment so that it is able to start the Azure CLI binary.

**Comment by JK87iab** [comment]
Hi thx for the reply. 

It worked after I run the VS command pallet: **Install code command in Path** and run vs code one time from terminal.

Thx
