### ISSUE TITLE
[BUG] Extension does not recognize custom databricks domains(reopen of bug #664)

### ISSUE THREAD

**Issue by ajsiripuram-npss** [databricks/databricks-vscode#884]
This is a reopen of bug # 664 extension does not recognize custom databricks domains
@kartikgupta-db  After the merge, the Databricks VS extension is still not accepting custom domain names. I get the same error "Not a databricks host" Please help address this issue and fix it. Thank you
Databricks extension version 1.1.3

**Comment by kartikgupta-db** [comment]
@ajsiripuram-npss this will be released in the next release (happening Monday). I will leave the bug open. Let me know if it still does not work for you.

**Comment by ajsiripuram-npss** [comment]
@kartikgupta-db oh sorry thought it was merged and released, hence I retried it. Will check on Monday, Thank you!

**Comment by kartikgupta-db** [comment]
@ajsiripuram-npss the release has just gone out. I am closing the issue for now, but feel free to open it again if you are still having issues. 

We **do not** guarantee full feature support for custom domains (because they include Private Virtual Clouds as well where critical requirements such as files in workspaces are disabled). But this should unblock you to use the features that do work.
