### ISSUE TITLE
[BUG] Requires static resources from databricks-prod-cloudfront.cloud.databricks.com to render outputs

### ISSUE THREAD

**Issue by abij** [databricks/databricks-vscode#933]
**Describe the bug**
The plugin requires access to external domain (databricks-prod-cloudfront.cloud.databricks.com) to render output. We are using the plugin in an isolated environment where internet access is not allowed. The domain databricks-prod-cloudfront.cloud.databricks.com is blocked. And the static resource can not be obtained, this could be embedded into the plugin?

> Network Error
> Please check your network connection and try again.
> 
> Could not load a required resource: https://databricks-prod-cloudfront.cloud.databricks.com/static/aba08f77438558ccb293e1cca232e27ecb324b4333b35e375b94c2215aa08a41/js/notebook-main.js

**To Reproduce**
1. Block internet access
2. Render output

**Screenshots**
![a9ykpyxq](https://github.com/databricks/databricks-vscode/assets/1022013/019a1215-c787-4d75-89e8-898782d4d248)

**System information:**

1. VSCode on Windows (one of the most recent versions)
2. Databricks Extension Version 1.2.2

**Databricks Extension Logs**
<dont have this>

**Additional context**
By default blocked all (outgoing) internet traffic

**Comment by kartikgupta-db** [comment]
Hi. Currently we are limited by our APIs, which only return an HTML response, where the js is pulled from static. As a workaround, you can try clicking on the "Task run ID:" field to open the task output in the databricks web ui. 

This limitation should not occur for other run modes - Run locally using Databricks Connect V2 and "Upload and Run File on Databricks". 

I will forward this request to the relevant team internally, since exporting a job run as a portable file (ideally PDF) would be an amazing feature to have.
